### ISSUE TITLE
Requests for Tingus

### ISSUE THREAD

**Issue by Gilgabourne** [quantsolutions/ui_test_creator#62]
Hi Georg

In our descussion, we had last week ( 30 July '18).  TL;DR

-  Tingus having its own time unit

- Ability to query Databases for results and advance tests

Firstly, the Tingus application tries to complete the scripted tasks asap. Which is good for data capturing. But since we are dealing some screen components which take a numerous time to load. The tests tend to fail due to it can't find the next image. A good example is when we perform an update to our Tariff structures. 

We did come up with two ways where we can handle this:

- 1-second sleep/wait build in for each action by default
- Config file where we can manually adjust the time (Decimal time, in a way, up to you)

Our second request is if you could give us some sort of connection to a database so where we can perform in deep testing. (Like we did in GAT). For us, this will open the window to write complicated, but more accurate tests. (Mostly for select specific invoice no, correctly build from both front and backend posting, XML posting etc.)

Bug me if anything is unclear or more information is needed.

Bart

**Comment by GeorgSteyn** [comment]
Duly Noted! 
Please, can you make this two issues? Because this issue is handling two different topics.

**Comment by Gilgabourne** [comment]
Will do.
